// Generated by CoffeeScript 1.12.7
(function() {
  var app, app_version, couchapp, p_fun;

  app = 'wandering-country';

  app_version = '1.0';

  p_fun = require('coffeescript-helpers').p_fun;

  couchapp = function(arg) {
    var extra, normalize_account;
    normalize_account = arg.normalize_account;
    extra = "var normalize_account = " + normalize_account + ";";
    return {
      _id: "_design/" + app,
      version: app_version,
      language: 'javascript',
      views: {
        numbers_by_domain: {
          map: p_fun(function(doc) {
            var m;
            if (!((doc.type != null) && doc.type === 'number')) {
              return;
            }
            if (!(m = doc._id.match(/^number:[^@]+@(.+)$/))) {
              return;
            }
            emit(m[1]);
          }),
          reduce: '_count'
        },
        endpoints_by_domain: {
          map: p_fun(function(doc) {
            var m;
            if (!((doc.type != null) && doc.type === 'endpoint')) {
              return;
            }
            if (!(m = doc._id.match(/^endpoint:[^@]+@(.+)$/))) {
              return;
            }
            emit(m[1]);
          })
        },
        devices: {
          map: p_fun(extra, function(doc) {
            var account;
            if (!((doc.type != null) && doc.type === 'device')) {
              return;
            }
            if (doc.disabled) {
              return;
            }
            if (doc.account != null) {
              account = normalize_account(doc.account);
              emit(['account', account], doc.device);
            }
          })
        },
        number_domains: {
          map: p_fun(extra, function(doc) {
            var account;
            if (!((doc.type != null) && doc.type === 'number_domain')) {
              return;
            }
            if (doc.disabled) {
              return;
            }
            if (doc.account != null) {
              account = normalize_account(doc.account);
              emit(['account', account], doc.number_domain);
            }
          })
        },
        endpoints: {
          map: p_fun(extra, function(doc) {
            var account, m;
            if (!((doc.type != null) && doc.type === 'endpoint')) {
              return;
            }
            if (doc.disabled) {
              return;
            }
            if (doc.account != null) {
              account = normalize_account(doc.account);
              emit(['account', account], doc.endpoint);
            }
            m = doc._id.match(/^endpoint:[^@]+@(.+)$/);
            if ((m != null ? m[1] : void 0) != null) {
              emit(['domain', m[1]], doc.endpoint);
            }
            if (doc.number_domain != null) {
              emit(['number_domain', doc.number_domain], doc.endpoint);
            }
          })
        },
        local_numbers: {
          map: p_fun(extra, function(doc) {
            var account, m;
            if (!((doc.type != null) && doc.type === 'number')) {
              return;
            }
            if (!(m = doc._id.match(/^number:[^@]+@(.+)$/))) {
              return;
            }
            if (doc.disabled) {
              return;
            }
            if (doc.account != null) {
              account = normalize_account(doc.account);
              emit(['account', account], doc.number);
            }
            if (m[1] != null) {
              emit(['number_domain', m[1]], doc.number);
            }
            if (doc.endpoint != null) {
              emit(['endpoint', doc.endpoint], doc.number);
            }
          })
        },
        global_numbers: {
          map: p_fun(extra, function(doc) {
            var account, m;
            if (!((doc.type != null) && doc.type === 'number')) {
              return;
            }
            if (m = doc._id.match(/^number:[^@]+@(.+)$/)) {
              return;
            }
            if (doc.disabled) {
              return;
            }
            if (doc.account != null) {
              account = normalize_account(doc.account);
              emit(['account', account]);
            }
            if (doc.local_number != null) {
              emit(['local_number', doc.local_number]);
            }
          })
        }
      }
    };
  };

  module.exports = {
    app: app,
    couchapp: couchapp
  };

}).call(this);
