// Generated by CoffeeScript 1.12.4
(function() {
  var PouchDB, debug, get_client_db, seem;

  seem = require('seem');

  debug = (require('debug'))('wandering-country:client-db');

  PouchDB = require('shimaore-pouchdb');

  module.exports = get_client_db = seem(function(ev) {
    var db, user_db;
    db = this.cfg.prov;
    user_db = (function(_this) {
      return function(name) {
        return new PouchDB(_this.cfg.userdb_base_uri + '/' + name);
      };
    })(this);
    return {
      db: db,
      user_db: user_db
    };
  });

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VydmVyLWRiLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsic2VydmVyLWRiLmNvZmZlZS5tZCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUk7QUFBQSxNQUFBOztFQUFBLElBQUEsR0FBTyxPQUFBLENBQVEsTUFBUjs7RUFDUCxLQUFBLEdBQVEsQ0FBQyxPQUFBLENBQVEsT0FBUixDQUFELENBQUEsQ0FBa0IsNkJBQWxCOztFQUVSLE9BQUEsR0FBVSxPQUFBLENBQVEsa0JBQVI7O0VBR1YsTUFBTSxDQUFDLE9BQVAsR0FBaUIsYUFBQSxHQUFnQixJQUFBLENBQUssU0FBQyxFQUFEO0FBSXBDLFFBQUE7SUFBQSxFQUFBLEdBQUssSUFBQyxDQUFBLEdBQUcsQ0FBQztJQUlWLE9BQUEsR0FBVSxDQUFBLFNBQUEsS0FBQTthQUFBLFNBQUMsSUFBRDtlQUNSLElBQUksT0FBSixDQUFZLEtBQUMsQ0FBQSxHQUFHLENBQUMsZUFBTCxHQUF1QixHQUF2QixHQUE2QixJQUF6QztNQURRO0lBQUEsQ0FBQSxDQUFBLENBQUEsSUFBQTtXQUdWO01BQUMsSUFBQSxFQUFEO01BQUksU0FBQSxPQUFKOztFQVhvQyxDQUFMO0FBTmpDIiwic291cmNlc0NvbnRlbnQiOlsiICAgIHNlZW0gPSByZXF1aXJlICdzZWVtJ1xuICAgIGRlYnVnID0gKHJlcXVpcmUgJ2RlYnVnJykgJ3dhbmRlcmluZy1jb3VudHJ5OmNsaWVudC1kYidcblxuICAgIFBvdWNoREIgPSByZXF1aXJlICdzaGltYW9yZS1wb3VjaGRiJ1xuICAgICMgUG91Y2hEQi5wbHVnaW4gcmVxdWlyZSAncG91Y2hkYi1maW5kJyAjIGluIENvdWNoREIgMi4wXG5cbiAgICBtb2R1bGUuZXhwb3J0cyA9IGdldF9jbGllbnRfZGIgPSBzZWVtIChldikgLT5cblxuYG5pbWJsZS1kaXJlY3Rpb25gIGNvbnZlbnRpb25cblxuICAgICAgZGIgPSBAY2ZnLnByb3ZcblxuYHdlbGwtZ3Jvb21lZC1lYXJ0aGAvYGh1Z2UtcGxheWAgY29udmVudGlvbnNcblxuICAgICAgdXNlcl9kYiA9IChuYW1lKSA9PlxuICAgICAgICBuZXcgUG91Y2hEQiBAY2ZnLnVzZXJkYl9iYXNlX3VyaSArICcvJyArIG5hbWVcblxuICAgICAge2RiLHVzZXJfZGJ9XG4iXX0=
//# sourceURL=/srv/home/stephane/Artisan/Managed/Telecoms/wandering-country/server-db.coffee.md