// Generated by CoffeeScript 1.12.4
(function() {
  var sleep;

  module.exports = sleep = function(timeout) {
    return new Promise(function(resolve) {
      return setTimeout((function() {
        return resolve();
      }), timeout);
    });
  };

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2xlZXAuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJzbGVlcC5jb2ZmZWUubWQiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFJO0FBQUEsTUFBQTs7RUFBQSxNQUFNLENBQUMsT0FBUCxHQUFpQixLQUFBLEdBQVEsU0FBQyxPQUFEO1dBQ3ZCLElBQUksT0FBSixDQUFZLFNBQUMsT0FBRDthQUNWLFVBQUEsQ0FBVyxDQUFDLFNBQUE7ZUFBRyxPQUFBLENBQUE7TUFBSCxDQUFELENBQVgsRUFBMkIsT0FBM0I7SUFEVSxDQUFaO0VBRHVCO0FBQXpCIiwic291cmNlc0NvbnRlbnQiOlsiICAgIG1vZHVsZS5leHBvcnRzID0gc2xlZXAgPSAodGltZW91dCkgLT5cbiAgICAgIG5ldyBQcm9taXNlIChyZXNvbHZlKSAtPlxuICAgICAgICBzZXRUaW1lb3V0ICgtPiByZXNvbHZlKCkpLCB0aW1lb3V0XG4iXX0=
//# sourceURL=/srv/home/stephane/Artisan/Managed/Telecoms/wandering-country/sleep.coffee.md